name: simulatorORCSE4529
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - matplotlib
  - pandas
  - pathlib
  - numpy
  - scipy
  - tqdm
  - joblib
  - jsons
  - seaborn
prefix: /Users/salim/miniconda3/envs/simulatorORCSE4529
